runtime: python
env: flex
entrypoint: uwsgi --ini saleor/wsgi/uwsgi.ini

runtime_config:
  python_version: 3

beta_settings:
  cloud_sql_instances: ${SQL_STRING}

skip_files:
  - Dockerfile
  - media/
  - node_modules/
  - docs/
  - static/
  - saleor/static/assets
  - ^(.*/)?\.css$
  - ^(.*/)?\.log$
  - ^(.*/)?\.pot$
  - ^(.*/)?\.pyc$

env_variables:
  REDIS_URL: ${REDIS_URL}
  DATABASE_URL: ${DATABASE_URL}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  EMAIL_URL: ${EMAIL_URL}
  OPENEXCHANGERATES_API_KEY: ${OPENEXCHANGERATES_API_KEY}
  SECRET_KEY: ${SECRET_KEY}
  STATIC_URL: ${STATIC_URL}
  GOOGLE_ANALYTICS_TRACKING_ID: ${GOOGLE_ANALYTICS_TRACKING_ID}
  STRIPE_SK: ${STRIPE_SK}
  STRIPE_PK: ${STRIPE_PK}
  MAX_CART_LINE_QUANTITY: ${MAX_CART_LINE_QUANTITY}
  ALLOWED_HOSTS: '*'
  DEBUG: 'False'

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
